#©2016-2017 EdgeVerve Systems Limited (a fully owned Infosys subsidiary),Bangalore, India. All Rights Reserved.

- name: Setup docker storage in rhel family
  include: storage_setup_rhel.yml
  when: ansible_os_family == 'RedHat' and (directLVMstorage == True or directLVMstorage == "yes")

