#©2016-2017 EdgeVerve Systems Limited (a fully owned Infosys subsidiary),Bangalore, India. All Rights Reserved.

- name: Create backup folder for gitlab
  file: path={{cepfolder}}/cep/gitlab state=directory
  when: installgitlab == True or installgitlab == "yes"
  
- name: Create prometheus folder for configuration
  file: path={{cepfolder}}/cep/prometheus state=directory
  when: installmonitor == True or installmonitor == "yes"

- name: Create alertmanager folder for configuration
  file: path={{cepfolder}}/cep/alertmanager state=directory
  when: installmonitor == True or installmonitor == "yes"
  
- name: Create grafana folder for configuration
  file: path={{cepfolder}}/cep/grafana/dashboards state=directory
  when: installmonitor == True or installmonitor == "yes" 
  
- name: Copy config files
  template: "src={{item.src}} dest={{item.dest}}"
  with_items:
    -
      dest: "{{cepfolder}}/cep/prometheus/prometheus.conf"
      src: "prometheus/prometheus.j2"
    -
      dest: "{{cepfolder}}/cep/prometheus/alert.rules"
      src: "prometheus/alert.rules"
    -
      dest: "{{cepfolder}}/cep/alertmanager/alertmanager.conf"
      src: "prometheus/alertmanager.conf"
  when: installmonitor == True or installmonitor == "yes"
  
