#©2016-2017 EdgeVerve Systems Limited (a fully owned Infosys subsidiary),Bangalore, India. All Rights Reserved.

#Install nfs-utils
- name: "Install nfs-utils"
  yum: 
    name: nfs-utils
    state: present
  environment:
    http_proxy: "{{http_proxy}}"
    https_proxy: "{{https_proxy}}" 
    no_proxy: "{{no_proxy}}"
  when: setupNFS == True or setupNFS == "yes"

- name: Create folder for cep data
  file: path={{cepfolder}}/cep/cep-data state=directory
    
#mount -t nfs {{nfsserver_ip}}:{{nfsshare}}/evfpaasshare /etc/evfpaasshare
- name: mount NFS share folder
  mount:
    path: "{{cepfolder}}/cep/cep-data" 
    src: "{{  hostvars[groups['NFSServer'][0]]['inventory_hostname'] }}:{{NFSSharePath}}" 
    fstype: nfs4
    opts: nofail,auto,noatime,rw,user 
    state: mounted    
  when: setupNFS == True or setupNFS == "yes"

- name: Create backup folder for registry
  file: path={{cepfolder}}/cep/cep-data/registry state=directory
  
- name: Create backup folder for cep-portal
  file: path={{cepfolder}}/cep/cep-data/cep-portal state=directory

- name: Create backup folder for prometheus
  file: path={{cepfolder}}/cep/cep-data/prometheus state=directory
  when: installmonitor == True or installmonitor == "yes"
  
- name: Create backup folder for alertmanager
  file: path={{cepfolder}}/cep/cep-data/alertmanager state=directory
  when: installmonitor == True or installmonitor == "yes"

- name: Create backup folder for grafana
  file: path={{cepfolder}}/cep/cep-data/grafana state=directory  
  when: installmonitor == True or installmonitor == "yes"

- name: Create backup folder for gitlab
  file: path={{cepfolder}}/cep/cep-data/gitlab state=directory
  when: installgitlab == True or installgitlab == "yes"
  
- name: Create prometheus folder for configuration
  file: path={{cepfolder}}/cep/prometheus state=directory
  when: installmonitor == True or installmonitor == "yes"

- name: Create cep-portal folder for configuration
  file: path={{cepfolder}}/cep/cep-portal state=directory


- name: Create alertmanager folder for configuration
  file: path={{cepfolder}}/cep/alertmanager state=directory
  when: installmonitor == True or installmonitor == "yes"
  
- name: Copy config files
  template: "src={{item.src}} dest={{item.dest}}"
  with_items:
    -
      dest: "{{cepfolder}}/cep/prometheus/prometheus.conf"
      src: "prometheus/prometheus.j2"
    -
      dest: "{{cepfolder}}/cep/prometheus/alert.rules"
      src: "prometheus/alert.rules"
    -
      dest: "{{cepfolder}}/cep/alertmanager/alertmanager.conf"
      src: "prometheus/alertmanager.conf"
    -
      dest: "{{cepfolder}}/cep/cep-portal/endpoint-jsonArr.json"
      src: "cep-portal/endpoint-jsonArr.j2"
  register: prom_conf_changed
  when: installmonitor == True or installmonitor == "yes"

