#©2016-2017 EdgeVerve Systems Limited (a fully owned Infosys subsidiary),Bangalore, India. All Rights Reserved.

- name: set variable of EE repository URL 
  set_fact:
    dockerUrl: "https://storebits.docker.com/ee/m/{{ docker_ee_subscription }}/rhel"
    
- name: Store EE repository URL 
  shell: echo "{{ dockerUrl }}" > /etc/yum/vars/dockerurl

- name: Echo OS version
  debug: msg="ansible_distribution_version={{ ansible_distribution_version }}"

- name: Store your OS version
  shell: echo "{{ ansible_distribution_version }}" > /etc/yum/vars/dockerosversion

- name: Add docker repo
  shell: yum-config-manager --add-repo "{{ dockerUrl }}/docker-ee.repo"
  environment:
    http_proxy: "{{http_proxy}}"
    https_proxy: "{{https_proxy}}" 
    no_proxy: "{{no_proxy}}"

- name: "Install docker-ee for RHEL"
  yum: 
    name: docker-ee
    state: present
    enablerepo: rhel-7-server-extras-rpms
  environment:
    http_proxy: "{{http_proxy}}"
    https_proxy: "{{https_proxy}}" 
    no_proxy: "{{no_proxy}}"
  when:
    ansible_distribution == 'RedHat'
  
- name: "Install docker-ee for CentOS"
  yum: 
    name: docker-ee
    state: present
  environment:
    http_proxy: "{{http_proxy}}"
    https_proxy: "{{https_proxy}}" 
    no_proxy: "{{no_proxy}}" 
  when:
    ansible_distribution == "CentOS"
    
- name: Enable docker ports in firewalld
  firewalld: port={{item.port}} permanent=true state=enabled
  with_items:
    - { port: 80/tcp }
    - { port: 443/tcp }
    - { port: 2375/tcp }
    - { port: 2377/tcp }
    - { port: 7946/tcp }
    - { port: 7946/udp }
    - { port: 4789/tcp }
    - { port: 4789/udp }
    - { port: 12201/udp } #graylog udp port
    - { port: 9323/tcp } #docker metrics port
    - { port: 8080/tcp } #cadvisor port
    - { port: 4500/tcp } #dtr https port
    - { port: 4501/tcp } #dtr http port
    - { port: 4433/tcp } #ucp port #1
    - { port: 12379/tcp } #ucp port #2
    - { port: 12383/tcp } #ucp port #3
    - { port: 12382/tcp } #ucp port #4
    - { port: 12376/tcp } #ucp port #5
    - { port: 12381/tcp } #ucp port #6
    - { port: 12387/tcp } #ucp port #7
    - { port: 12380/tcp } #ucp port #8
    - { port: 12384/tcp } #ucp port #9
    - { port: 12386/tcp } #ucp port #10
    - { port: 12385/tcp } #ucp port #11
  register: firewalld_op_ee
    
