#©2016-2017 EdgeVerve Systems Limited (a fully owned Infosys subsidiary),Bangalore, India. All Rights Reserved.

# Installing cadvisor and running in each host (Container option has issue -> https://github.com/google/cadvisor/issues/771 )

- name: create {{cepfolder}}/cep/cAdvisor folder
  file: path={{cepfolder}}/cep/cAdvisor state=directory 
    
- name: unarchive cadvisor
  unarchive:
    src: "roles/cadvisor/templates/cadvisor.tar.gz"
    dest: "{{cepfolder}}/cep/cAdvisor/"
    mode: u+x
      
- name: Copy cadvisor service file
  template: src=cadvisor.service dest=/usr/lib/systemd/system/
  register: cadvisor_service_file_changed

- name: Reload systemd
  command: systemctl daemon-reload
  when: (cadvisor_service_file_changed | changed)

- name: service start cadvisor
  service: name=cadvisor state=started enabled=yes
 
