#©2016-2017 EdgeVerve Systems Limited (a fully owned Infosys subsidiary),Bangalore, India. All Rights Reserved.

- name: Check that the grafana data exists
  stat:
    path: "{{cepfolder}}/cep-data/grafana/grafana.db"
  register: stat_result

- name: copy grafana data files if doesn't exist
  copy: 
    src: "roles/monitoring/templates/grafana/grafana.db"
    dest: "{{cepfolder}}/cep-data/grafana/grafana.db"
  when: stat_result.stat.exists == False 

- name: spin grafana service
  shell: >
         docker service create  --detach=false --with-registry-auth 
         --mount target=/var/lib/grafana,source={{cepfolder}}/cep-data/grafana,type=bind
         -e FORCE_SSL=yes 
         -e SERVICE_PORTS="3000" 
         -e VIRTUAL_HOST="https://grafana.{{domainname}},grafana.{{domainname}}" 
         -e "GF_SERVER_ROOT_URL=https://grafana.{{domainname}}" 
         -e "PROMETHEUS_ENDPOINT=http://prometheus-server:9090" 
         --constraint "node.hostname == $HOSTNAME"
         --network router_network 
         --name cep-grafana-server 
         {{ grafana }}
  when: (setupNFS == False or setupNFS == "no")

- name: spin grafana service
  shell: >
         docker service create  --detach=false --with-registry-auth 
         --mount target=/var/lib/grafana,source={{cepfolder}}/cep-data/grafana,type=bind
         -e FORCE_SSL=yes 
         -e SERVICE_PORTS="3000" 
         -e VIRTUAL_HOST="https://grafana.{{domainname}},grafana.{{domainname}}" 
         -e "GF_SERVER_ROOT_URL=https://grafana.{{domainname}}" 
         -e "PROMETHEUS_ENDPOINT=http://prometheus-server:9090" 
         --network router_network 
         --name cep-grafana-server 
         {{ grafana }}
  when: (setupNFS == True or setupNFS == "yes")