#©2016-2017 EdgeVerve Systems Limited (a fully owned Infosys subsidiary),Bangalore, India. All Rights Reserved.

- name: join worker nodes to cluster
  block:
   - shell: >
            docker swarm join
            --token={{ hostvars[groups['swarm_manager_operational'][0]]['swarm_worker_token']['stdout'] }} --listen-addr=0.0.0.0:2377
            {{ groups['swarm_manager_ips'][0] }}:2377
  rescue:
   - name: Join worker nodes failed
     fail: msg="Make sure if {{ groups['swarm_manager_ips'] }} along with all the node ips is in no_proxy[{{no_proxy}}] env if proxy is present"