#©2016-2017 EdgeVerve Systems Limited (a fully owned Infosys subsidiary),Bangalore, India. All Rights Reserved.

- name: check if overlay network is present
  shell: "docker network ls | grep router_network | wc -l"
  register: existing_network_op

- name: create a overlay network for router
  shell: "docker network create -d overlay router_network"
  when: existing_network_op.stdout == "0"
    
- name: check if router is already present
  shell: "docker service ls | grep cep_router | wc -l"
  register: existing_router_op

- set_fact:
    cert_file_path: "SSLCertificates/{{domainname}}/haproxy.pem"

- set_fact:
    cert_content: "{{ lookup('file', cert_file_path) }}"
  
- name: install router in docker-ce environment
  include: router_docker_ce.yml
  when: docker_ee_subscription == ""
  
- name: install router in docker-ce environment
  include: router_docker_ee.yml
  when: docker_ee_subscription != ""
  
  